# Default image (https://hub.docker.com/_/php/)
image: ubuntu:18.04

variables:
  TZ: "Europe/Budapest"

stages:
  - build

before_script:
  - apt-get update -yqq
  - apt-get install -yqq build-essential cmake
  - apt-get install -yqq libboost-all-dev libgdal-dev
  - apt-get install -yqq libopenmpi-dev
  - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
  - apt-get install -yqq libopencv-dev

# Build
build:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make
