stages:
  - build
  - test

variables:
  # No interactive timezone dialog for tzdata
  DEBIAN_FRONTEND: noninteractive

# SAST
include:
  - template: Jobs/SAST.gitlab-ci.yml

# Build
.build:
  stage: build
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq build-essential cmake
    - apt-get install -yqq libboost-all-dev libgdal-dev libopencv-dev
    - apt-get install -yqq libopenmpi-dev
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make

build_focal:
  extends: .build
  image: ubuntu:20.04

build_jammy:
  extends: .build
  image: ubuntu:22.04
