name: Build project

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Update package repository
      run: sudo apt-get update
      
    - name: Install required packages
      run: sudo apt-get install libboost-all-dev libgdal-dev libopenmpi-dev
      
    - name: Create build environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE